version: "3.9"

services:
  go-chibi-app:
    container_name: go-chibi-url
    build: .
    environment:
      DATABASE_URL: "host:go_db user=postgres password=postgres dbname=postgress sslmode=disabled"
    ports:
      - "8080:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgressql/data

volumes:
  pgdata: {}
